services:
  - type: web
    name: todolist-api
    env: docker
    repo: https://github.com/your-repo/BE_ToDoList # Replace with your GitHub repo URL
    dockerfilePath: ./ToDoList_FS/Dockerfile
    region: singapore # Choose appropriate region
    plan: free # You can change to paid plans as needed
    envVars:
      - key: MONGO_CONNECTION_STRING
        value: mongodb+srv://duyentran2491991:iPQTfs3rbS3Q1CBk@todolist.ineop.mongodb.net/?retryWrites=true&w=majority&ssl=true
      - key: MONGO_TLS
        value: true
      - key: MONGO_SSL
        value: true
      - key: JWT_SECRET
        value: banhxeo0210_abc1234567890abcdef
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
    healthCheckPath: /swagger
    # Optional: Add the following if your application needs to define custom domains
    # domains:
    #  - api.yourdomain.com 