services:
  - type: web
    name: todolist-api
    env: docker
    repo: https://github.com/your-repo/BE_ToDoList # Replace with your GitHub repo URL
    dockerfilePath: ./ToDoList_FS/Dockerfile
    region: singapore # Choose appropriate region
    plan: free # You can change to paid plans as needed
    envVars:
      - key: PORT
        value: 8080
      - key: MONGO_CONNECTION_STRING
        value: mongodb+srv://duyentran2491991:iPQTfs3rbS3Q1CBk@todolist.ineop.mongodb.net/?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: banhxeo0210_abc1234567890abcdef
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
    healthCheckPath: /health
    buildCommand: docker build -t todolist-api -f ToDoList_FS/Dockerfile .
    startCommand: docker run -p 8080:8080 -e PORT=8080 todolist-api
    # Optional: Add the following if your application needs to define custom domains
    # domains:
    #  - api.yourdomain.com 